steps:
- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/mycurriculumvitae-296316/marvintensuan",
         "-s", "mycurriculumvitae-296316:asia-east1:myinstance",
         "--", "python", "manage.py", "makemigrations"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/mycurriculumvitae-296316/marvintensuan",
         "-s", "mycurriculumvitae-296316:asia-east1:myinstance",
         "--", "python", "manage.py", "migrate"]

