# Generated by Django 3.1.3 on 2020-12-30 11:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('mt_backend', '0002_cpd_sdl_onlinecourse_sdl_webinars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdl_onlinecourse',
            name='facilitator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sdl_onlinecourse',
            name='link_to_certificate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sdl_onlinecourse',
            name='onlinecourse_date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sdl_webinars',
            name='html_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sdl_webinars',
            name='organizer',
            field=models.CharField(max_length=150),
        ),
    ]
